PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
INSERT INTO migrations VALUES(1,'0001_01_01_000000_create_users_table',1);
INSERT INTO migrations VALUES(2,'0001_01_01_000001_create_cache_table',1);
INSERT INTO migrations VALUES(3,'0001_01_01_000002_create_jobs_table',1);
INSERT INTO migrations VALUES(4,'2024_11_13_070450_create_merk_table',2);
INSERT INTO migrations VALUES(5,'2024_11_13_070946_create_personal_access_tokens_table',3);
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("email"));
CREATE TABLE IF NOT EXISTS "sessions" ("id" varchar not null, "user_id" integer, "ip_address" varchar, "user_agent" text, "payload" text not null, "last_activity" integer not null, primary key ("id"));
CREATE TABLE IF NOT EXISTS "cache" ("key" varchar not null, "value" text not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "cache_locks" ("key" varchar not null, "owner" varchar not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "jobs" ("id" integer primary key autoincrement not null, "queue" varchar not null, "payload" text not null, "attempts" integer not null, "reserved_at" integer, "available_at" integer not null, "created_at" integer not null);
CREATE TABLE IF NOT EXISTS "job_batches" ("id" varchar not null, "name" varchar not null, "total_jobs" integer not null, "pending_jobs" integer not null, "failed_jobs" integer not null, "failed_job_ids" text not null, "options" text, "cancelled_at" integer, "created_at" integer not null, "finished_at" integer, primary key ("id"));
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "merk" ("id" integer primary key autoincrement not null, "nama" varchar not null, "desc" text not null, "logo" varchar not null, "created_at" datetime, "updated_at" datetime, "asal" VARCHAR(50) NULL, "filosofi" VARCHAR(50) NULL);
INSERT INTO merk VALUES(7,'rendang','Rendang adalah masakan khas Minangkabau yang terbuat dari daging sapi yang dimasak dengan santan dan bumbu rempah hingga kering. Proses memasaknya memakan waktu lama untuk menghasilkan cita rasa kaya dan tekstur empuk.','https://i.imgur.com/dCN8B89.jpeg','2024-12-16 08:49:17','2024-12-16 08:54:02','jawa','Rendang melambangkan kesabaran, ketekunan, dan penghormatan karena pembuatannya membutuhkan waktu panjang dan perhatian detail.');
INSERT INTO merk VALUES(8,'pempek','Pempek Palembang adalah makanan khas dari Palembang yang terbuat dari ikan giling dan sagu, disajikan dengan kuah cuko berasa asam, manis, dan pedas. Varian utamanya meliputi kapal selam, lenjer, adaan, dan kulit.','https://i.imgur.com/qeSBZHh.jpeg','2024-12-16 08:52:35','2024-12-16 08:57:47','palembang','Pempek melambangkan kesederhanaan, keuletan, dan harmoni hidup melalui perpaduan rasa gurih dan kuah cuko. Ragam variannya mencerminkan keberagaman dan persatuan masyarakat Palembang.');
INSERT INTO merk VALUES(9,'nasi tumpeng','Nasi tumpeng adalah sajian berbentuk kerucut dari nasi kuning atau putih, dikelilingi lauk-pauk seperti ayam, tempe, telur, dan sambal goreng, biasanya disajikan untuk acara syukuran.','https://i.imgur.com/mCxdV7T.jpeg','2024-12-16 08:58:42','2024-12-16 09:02:40','jawa','Tumpeng melambangkan rasa syukur, keseimbangan hidup, dan hubungan harmonis antara manusia, alam, dan Tuhan.');
INSERT INTO merk VALUES(10,'sate','Sate adalah potongan kecil daging yang ditusuk dengan bambu lalu dibakar, disajikan dengan bumbu kacang atau kecap manis. Varian populer meliputi sate ayam, sate kambing, dan sate maranggi.','https://i.imgur.com/2PTYsCX.jpeg','2024-12-16 09:04:54','2024-12-16 09:04:54','jawa','Sate menggambarkan persatuan karena tiap tusuk menyatukan berbagai bahan menjadi satu hidangan nikmat.');
INSERT INTO merk VALUES(11,'papeda','Sate adalah potongan kecil daging yang ditusuk dengan bambu lalu dibakar, disajikan dengan bumbu kacang atau kecap manis. Varian populer meliputi sate ayam, sate kambing, dan sate maranggi.','https://i.imgur.com/E00pRCU.jpeg','2024-12-16 09:09:52','2024-12-16 09:09:52','papua dan maluku','Papeda melambangkan ketahanan dan kebersamaan, karena dimakan bersama-sama dalam tradisi masyarakat setempat.');
INSERT INTO merk VALUES(12,'ayam betutu','Ayam betutu adalah hidangan khas Bali berupa ayam utuh yang dimasak dengan bumbu genep (rempah khas Bali) dan dimasak perlahan hingga empuk.','https://i.imgur.com/fFEIr3n.jpeg','2024-12-16 09:12:46','2024-12-16 09:15:39','bali','Ayam betutu melambangkan keseimbangan rasa dan spiritualitas, mencerminkan budaya Bali yang menghormati tradisi.');
INSERT INTO merk VALUES(13,'sop konro','Sop konro adalah sup khas Makassar berbahan dasar iga sapi yang dimasak dengan kuah rempah berwarna gelap dari kluwek.','https://i.imgur.com/kkJCG12.jpeg','2024-12-16 09:19:09','2024-12-16 09:19:09','Sulawesi Selatan','Sop konro melambangkan kekuatan dan daya tahan, mencerminkan karakter masyarakat Bugis-Makassar.');
INSERT INTO merk VALUES(14,'ayam taliwang','Ayam taliwang adalah masakan khas Lombok berupa ayam kampung yang dibakar dengan bumbu pedas khas Lombok.','https://i.imgur.com/CqsQaKk.jpeg','2024-12-16 09:20:13','2024-12-16 09:20:13','Nusa Tenggara Barat','Ayam taliwang melambangkan keberanian dan semangat, sesuai dengan rasa pedas yang menggugah selera.');
INSERT INTO merk VALUES(15,'Ikan Kuah Belimbing','Ikan kuah belimbing adalah masakan khas Maluku berupa ikan dimasak dengan bumbu rempah dan belimbing wuluh untuk cita rasa asam segar.','https://i.imgur.com/wahIzgC.jpeg','2024-12-16 09:22:08','2024-12-16 09:22:08','Maluku','Ikan kuah belimbing melambangkan kesegaran hidup dan keseimbangan dalam menghadapi dinamika kehidupan.');
INSERT INTO merk VALUES(16,'sasak rawon','Rawon khas Sasak menggunakan kuah hitam berbumbu kluwek, daging sapi, dan rempah yang menciptakan rasa kuat dan khas.','https://i.imgur.com/fdX8AMN.jpeg','2024-12-16 09:23:45','2024-12-16 09:23:45','Nusa Tenggara Barat','Rawon khas Sasak mencerminkan kekayaan budaya dan keberanian masyarakat Sasak dalam menciptakan cita rasa unik.');
CREATE TABLE IF NOT EXISTS "personal_access_tokens" ("id" integer primary key autoincrement not null, "tokenable_type" varchar not null, "tokenable_id" integer not null, "name" varchar not null, "token" varchar not null, "abilities" text, "last_used_at" datetime, "expires_at" datetime, "created_at" datetime, "updated_at" datetime);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('migrations',5);
INSERT INTO sqlite_sequence VALUES('merk',16);
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE INDEX "sessions_user_id_index" on "sessions" ("user_id");
CREATE INDEX "sessions_last_activity_index" on "sessions" ("last_activity");
CREATE INDEX "jobs_queue_index" on "jobs" ("queue");
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" on "personal_access_tokens" ("tokenable_type", "tokenable_id");
CREATE UNIQUE INDEX "personal_access_tokens_token_unique" on "personal_access_tokens" ("token");
COMMIT;
